/**
 * GET /api/agent/steps
 *
 * Returns the 4 form steps for the FAFSA Verification walkthrough.
 * In production these would be dynamically generated by WatsonX Orchestrate
 * based on the specific form and the student's pre-populated profile data.
 */
export async function GET() {
  return Response.json([
    {
      stepNumber: 1,
      question: 'What is your student ID number?',
      inputType: 'text',
      options: null,
      fieldName: 'studentId'
    },
    {
      stepNumber: 2,
      question: 'What is your expected graduation year?',
      inputType: 'select',
      options: ['2025', '2026', '2027', '2028'],
      fieldName: 'gradYear'
    },
    {
      stepNumber: 3,
      question: 'Have you had any changes to your financial situation this year?',
      inputType: 'yesno',
      options: ['Yes', 'No'],
      fieldName: 'financialChange'
    },
    {
      stepNumber: 4,
      question: 'What is your dependency status for this academic year?',
      inputType: 'yesno',
      options: ['Dependent', 'Independent'],
      fieldName: 'dependencyStatus'
    }
  ])
}
